name: Go

on:
  push:
    branches:
      - master

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
  
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Go environment
      uses: actions/setup-go@v2

    - name: Build
      run: go build ./cmd/...
    
    - name: Test
      run: |
        go test ./...
        go test -race ./...

  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v1
        with:
          version: v1.27
